name: LHCI

on:
    push:
        branches: [main, preview]
    pull_request:
        branches: [main, preview]

jobs:
    lighthouseci:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
            - uses: actions/checkout@v2

            - name: setup Node.js
            - uses: actions/setup-node@v1
              with:
                  node-version: 20
            - run: npm install && npm install -g @lhci/cli@0.8.x
            - run: npm run build
            - run: lhci autorun
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
